[package]
name = "sayeh-ffi"
description = "UniFFI bindings for Sayeh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
sayeh-core = { version = "0.1.0", path = "../sayeh-core", features = ["contacts"] }
thiserror.workspace = true
uniffi.workspace = true
