[package]
name = "xtask"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
quick-xml.workspace = true
rand_chacha.workspace = true
rand_core.workspace = true
sayeh-core = { path = "../sayeh-core", features = ["contacts"] }
serde_json.workspace = true
sha2.workspace = true
zeroize.workspace = true
