// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package ir.sayeh.ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_sayeh_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_sayeh_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "sayeh_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}














































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
//
// The `ffi_uniffi_contract_version` method and all checksum methods are put
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_sayeh_ffi_checksum_func_analyse_message(
): Short
fun uniffi_sayeh_ffi_checksum_func_analyse_transport_probe(
): Short
fun uniffi_sayeh_ffi_checksum_func_generate_transport_probe(
): Short
fun uniffi_sayeh_ffi_checksum_func_hide_password_file(
): Short
fun uniffi_sayeh_ffi_checksum_func_hide_password_text(
): Short
fun uniffi_sayeh_ffi_checksum_func_payload_capacity(
): Short
fun uniffi_sayeh_ffi_checksum_func_reveal_password_message(
): Short
fun uniffi_sayeh_ffi_checksum_func_scan_message(
): Short
fun uniffi_sayeh_ffi_checksum_func_strip_message_aggressive(
): Short
fun uniffi_sayeh_ffi_checksum_func_strip_message_safe(
): Short
fun ffi_sayeh_ffi_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "sayeh_ffi"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is
            // rather `InterfaceTooLargeException`, caused by too many methods
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            //
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }

    }

    // FFI functions
    fun uniffi_sayeh_ffi_fn_func_analyse_message(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_analyse_transport_probe(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_generate_transport_probe(uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_hide_password_file(`cover`: RustBuffer.ByValue,`fileName`: RustBuffer.ByValue,`bytes`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`carrier`: RustBuffer.ByValue,`createdAt`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_hide_password_text(`cover`: RustBuffer.ByValue,`secret`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`carrier`: RustBuffer.ByValue,`createdAt`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_payload_capacity(`carrier`: RustBuffer.ByValue,`contactMode`: Byte,`fileNameBytes`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_reveal_password_message(`text`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_scan_message(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_strip_message_aggressive(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_sayeh_ffi_fn_func_strip_message_safe(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_sayeh_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_sayeh_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_sayeh_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun ffi_sayeh_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_sayeh_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Byte
fun ffi_sayeh_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Byte
fun ffi_sayeh_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Short
fun ffi_sayeh_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Short
fun ffi_sayeh_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Int
fun ffi_sayeh_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Int
fun ffi_sayeh_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Long
fun ffi_sayeh_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Long
fun ffi_sayeh_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Float
fun ffi_sayeh_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Double
fun ffi_sayeh_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Pointer
fun ffi_sayeh_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_sayeh_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_sayeh_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_sayeh_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_sayeh_ffi_checksum_func_analyse_message() != 10859.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_analyse_transport_probe() != 65355.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_generate_transport_probe() != 49638.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_hide_password_file() != 15428.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_hide_password_text() != 9970.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_payload_capacity() != 23076.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_reveal_password_message() != 65504.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_scan_message() != 10312.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_strip_message_aggressive() != 24178.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_sayeh_ffi_checksum_func_strip_message_safe() != 6925.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/**
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Statistics from one disclosed carrier detector.
 */
data class AnalysisReport (
    var `carrier`: CarrierChoice,
    var `symbols`: kotlin.ULong,
    var `visibleScalars`: kotlin.ULong,
    var `density`: kotlin.Double,
    var `chiSquare`: kotlin.Double,
    var `longestRun`: kotlin.ULong,
    var `meanGap`: kotlin.Double,
    var `gapCoefficientOfVariation`: kotlin.Double,
    var `positionalEntropy`: kotlin.Double,
    var `suspicionScore`: kotlin.UByte,
    var `likelyDetectable`: kotlin.Boolean
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAnalysisReport: FfiConverterRustBuffer<AnalysisReport> {
    override fun read(buf: ByteBuffer): AnalysisReport {
        return AnalysisReport(
            FfiConverterTypeCarrierChoice.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: AnalysisReport) = (
            FfiConverterTypeCarrierChoice.allocationSize(value.`carrier`) +
            FfiConverterULong.allocationSize(value.`symbols`) +
            FfiConverterULong.allocationSize(value.`visibleScalars`) +
            FfiConverterDouble.allocationSize(value.`density`) +
            FfiConverterDouble.allocationSize(value.`chiSquare`) +
            FfiConverterULong.allocationSize(value.`longestRun`) +
            FfiConverterDouble.allocationSize(value.`meanGap`) +
            FfiConverterDouble.allocationSize(value.`gapCoefficientOfVariation`) +
            FfiConverterDouble.allocationSize(value.`positionalEntropy`) +
            FfiConverterUByte.allocationSize(value.`suspicionScore`) +
            FfiConverterBoolean.allocationSize(value.`likelyDetectable`)
    )

    override fun write(value: AnalysisReport, buf: ByteBuffer) {
            FfiConverterTypeCarrierChoice.write(value.`carrier`, buf)
            FfiConverterULong.write(value.`symbols`, buf)
            FfiConverterULong.write(value.`visibleScalars`, buf)
            FfiConverterDouble.write(value.`density`, buf)
            FfiConverterDouble.write(value.`chiSquare`, buf)
            FfiConverterULong.write(value.`longestRun`, buf)
            FfiConverterDouble.write(value.`meanGap`, buf)
            FfiConverterDouble.write(value.`gapCoefficientOfVariation`, buf)
            FfiConverterDouble.write(value.`positionalEntropy`, buf)
            FfiConverterUByte.write(value.`suspicionScore`, buf)
            FfiConverterBoolean.write(value.`likelyDetectable`, buf)
    }
}



/**
 * Hard payload ceiling and carrier expansion at that ceiling.
 */
data class CapacityReport (
    var `maxPayloadBytes`: kotlin.ULong,
    var `containerBytesAtLimit`: kotlin.ULong,
    var `carrierSymbolsAtLimit`: kotlin.ULong
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCapacityReport: FfiConverterRustBuffer<CapacityReport> {
    override fun read(buf: ByteBuffer): CapacityReport {
        return CapacityReport(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: CapacityReport) = (
            FfiConverterULong.allocationSize(value.`maxPayloadBytes`) +
            FfiConverterULong.allocationSize(value.`containerBytesAtLimit`) +
            FfiConverterULong.allocationSize(value.`carrierSymbolsAtLimit`)
    )

    override fun write(value: CapacityReport, buf: ByteBuffer) {
            FfiConverterULong.write(value.`maxPayloadBytes`, buf)
            FfiConverterULong.write(value.`containerBytesAtLimit`, buf)
            FfiConverterULong.write(value.`carrierSymbolsAtLimit`, buf)
    }
}



/**
 * A successful hide operation and non-secret size metadata.
 */
data class HiddenMessage (
    var `text`: kotlin.String,
    var `contentBytes`: kotlin.ULong,
    var `containerBytes`: kotlin.ULong,
    var `carrierSymbols`: kotlin.ULong,
    var `compressed`: kotlin.Boolean
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHiddenMessage: FfiConverterRustBuffer<HiddenMessage> {
    override fun read(buf: ByteBuffer): HiddenMessage {
        return HiddenMessage(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: HiddenMessage) = (
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterULong.allocationSize(value.`contentBytes`) +
            FfiConverterULong.allocationSize(value.`containerBytes`) +
            FfiConverterULong.allocationSize(value.`carrierSymbols`) +
            FfiConverterBoolean.allocationSize(value.`compressed`)
    )

    override fun write(value: HiddenMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`text`, buf)
            FfiConverterULong.write(value.`contentBytes`, buf)
            FfiConverterULong.write(value.`containerBytes`, buf)
            FfiConverterULong.write(value.`carrierSymbols`, buf)
            FfiConverterBoolean.write(value.`compressed`, buf)
    }
}



/**
 * Opened text or file bytes.
 */
data class OpenedMessage (
    var `isText`: kotlin.Boolean,
    var `text`: kotlin.String?,
    var `fileName`: kotlin.String?,
    var `bytes`: kotlin.ByteArray,
    var `counter`: kotlin.ULong,
    var `createdAt`: kotlin.ULong
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOpenedMessage: FfiConverterRustBuffer<OpenedMessage> {
    override fun read(buf: ByteBuffer): OpenedMessage {
        return OpenedMessage(
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: OpenedMessage) = (
            FfiConverterBoolean.allocationSize(value.`isText`) +
            FfiConverterOptionalString.allocationSize(value.`text`) +
            FfiConverterOptionalString.allocationSize(value.`fileName`) +
            FfiConverterByteArray.allocationSize(value.`bytes`) +
            FfiConverterULong.allocationSize(value.`counter`) +
            FfiConverterULong.allocationSize(value.`createdAt`)
    )

    override fun write(value: OpenedMessage, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`isText`, buf)
            FfiConverterOptionalString.write(value.`text`, buf)
            FfiConverterOptionalString.write(value.`fileName`, buf)
            FfiConverterByteArray.write(value.`bytes`, buf)
            FfiConverterULong.write(value.`counter`, buf)
            FfiConverterULong.write(value.`createdAt`, buf)
    }
}



/**
 * Result of measuring a returned transport probe.
 */
data class ProbeReport (
    var `recommendation`: CarrierChoice?,
    var `scalars`: List<ProbeScalar>
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProbeReport: FfiConverterRustBuffer<ProbeReport> {
    override fun read(buf: ByteBuffer): ProbeReport {
        return ProbeReport(
            FfiConverterOptionalTypeCarrierChoice.read(buf),
            FfiConverterSequenceTypeProbeScalar.read(buf),
        )
    }

    override fun allocationSize(value: ProbeReport) = (
            FfiConverterOptionalTypeCarrierChoice.allocationSize(value.`recommendation`) +
            FfiConverterSequenceTypeProbeScalar.allocationSize(value.`scalars`)
    )

    override fun write(value: ProbeReport, buf: ByteBuffer) {
            FfiConverterOptionalTypeCarrierChoice.write(value.`recommendation`, buf)
            FfiConverterSequenceTypeProbeScalar.write(value.`scalars`, buf)
    }
}



/**
 * Exact survival count for one probe scalar.
 */
data class ProbeScalar (
    var `codepoint`: kotlin.String,
    var `survived`: kotlin.UByte
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProbeScalar: FfiConverterRustBuffer<ProbeScalar> {
    override fun read(buf: ByteBuffer): ProbeScalar {
        return ProbeScalar(
            FfiConverterString.read(buf),
            FfiConverterUByte.read(buf),
        )
    }

    override fun allocationSize(value: ProbeScalar) = (
            FfiConverterString.allocationSize(value.`codepoint`) +
            FfiConverterUByte.allocationSize(value.`survived`)
    )

    override fun write(value: ProbeScalar, buf: ByteBuffer) {
            FfiConverterString.write(value.`codepoint`, buf)
            FfiConverterUByte.write(value.`survived`, buf)
    }
}



/**
 * Authenticated public container metadata.
 */
data class ScanReport (
    var `wireVersion`: kotlin.UByte,
    var `mode`: PayloadMode,
    var `carrier`: CarrierChoice,
    var `compressed`: kotlin.Boolean,
    var `errorCorrection`: kotlin.Boolean,
    var `containerBytes`: kotlin.ULong,
    var `carrierSymbols`: kotlin.ULong,
    var `argonMemoryKib`: kotlin.UInt?,
    var `argonPasses`: kotlin.UInt?,
    var `argonLanes`: kotlin.UByte?
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeScanReport: FfiConverterRustBuffer<ScanReport> {
    override fun read(buf: ByteBuffer): ScanReport {
        return ScanReport(
            FfiConverterUByte.read(buf),
            FfiConverterTypePayloadMode.read(buf),
            FfiConverterTypeCarrierChoice.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalUInt.read(buf),
            FfiConverterOptionalUInt.read(buf),
            FfiConverterOptionalUByte.read(buf),
        )
    }

    override fun allocationSize(value: ScanReport) = (
            FfiConverterUByte.allocationSize(value.`wireVersion`) +
            FfiConverterTypePayloadMode.allocationSize(value.`mode`) +
            FfiConverterTypeCarrierChoice.allocationSize(value.`carrier`) +
            FfiConverterBoolean.allocationSize(value.`compressed`) +
            FfiConverterBoolean.allocationSize(value.`errorCorrection`) +
            FfiConverterULong.allocationSize(value.`containerBytes`) +
            FfiConverterULong.allocationSize(value.`carrierSymbols`) +
            FfiConverterOptionalUInt.allocationSize(value.`argonMemoryKib`) +
            FfiConverterOptionalUInt.allocationSize(value.`argonPasses`) +
            FfiConverterOptionalUByte.allocationSize(value.`argonLanes`)
    )

    override fun write(value: ScanReport, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`wireVersion`, buf)
            FfiConverterTypePayloadMode.write(value.`mode`, buf)
            FfiConverterTypeCarrierChoice.write(value.`carrier`, buf)
            FfiConverterBoolean.write(value.`compressed`, buf)
            FfiConverterBoolean.write(value.`errorCorrection`, buf)
            FfiConverterULong.write(value.`containerBytes`, buf)
            FfiConverterULong.write(value.`carrierSymbols`, buf)
            FfiConverterOptionalUInt.write(value.`argonMemoryKib`, buf)
            FfiConverterOptionalUInt.write(value.`argonPasses`, buf)
            FfiConverterOptionalUByte.write(value.`argonLanes`, buf)
    }
}



/**
 * Carrier alphabets supported by wire v4.
 */

enum class CarrierChoice {

    ZERO_WIDTH,
    ZERO_WIDTH_COMPAT,
    VARIATION_SELECTORS,
    UNICODE_TAGS;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeCarrierChoice: FfiConverterRustBuffer<CarrierChoice> {
    override fun read(buf: ByteBuffer) = try {
        CarrierChoice.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: CarrierChoice) = 4UL

    override fun write(value: CarrierChoice, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Public mode metadata returned by a scan.
 */

enum class PayloadMode {

    PASSWORD,
    CONTACT;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePayloadMode: FfiConverterRustBuffer<PayloadMode> {
    override fun read(buf: ByteBuffer) = try {
        PayloadMode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PayloadMode) = 4UL

    override fun write(value: PayloadMode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







/**
 * Stable error boundary for Kotlin and Swift callers.
 */
sealed class SayehFfiException: kotlin.Exception() {

    class Failure(

        val `reason`: kotlin.String
        ) : SayehFfiException() {
        override val message
            get() = "reason=${ `reason` }"
    }


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<SayehFfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): SayehFfiException = FfiConverterTypeSayehFfiError.lift(error_buf)
    }


}

/**
 * @suppress
 */
public object FfiConverterTypeSayehFfiError : FfiConverterRustBuffer<SayehFfiException> {
    override fun read(buf: ByteBuffer): SayehFfiException {


        return when(buf.getInt()) {
            1 -> SayehFfiException.Failure(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: SayehFfiException): ULong {
        return when(value) {
            is SayehFfiException.Failure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
        }
    }

    override fun write(value: SayehFfiException, buf: ByteBuffer) {
        when(value) {
            is SayehFfiException.Failure -> {
                buf.putInt(1)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalUByte: FfiConverterRustBuffer<kotlin.UByte?> {
    override fun read(buf: ByteBuffer): kotlin.UByte? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUByte.read(buf)
    }

    override fun allocationSize(value: kotlin.UByte?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUByte.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UByte?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUByte.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalUInt: FfiConverterRustBuffer<kotlin.UInt?> {
    override fun read(buf: ByteBuffer): kotlin.UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: kotlin.UInt?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeCarrierChoice: FfiConverterRustBuffer<CarrierChoice?> {
    override fun read(buf: ByteBuffer): CarrierChoice? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeCarrierChoice.read(buf)
    }

    override fun allocationSize(value: CarrierChoice?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeCarrierChoice.allocationSize(value)
        }
    }

    override fun write(value: CarrierChoice?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeCarrierChoice.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeAnalysisReport: FfiConverterRustBuffer<List<AnalysisReport>> {
    override fun read(buf: ByteBuffer): List<AnalysisReport> {
        val len = buf.getInt()
        return List<AnalysisReport>(len) {
            FfiConverterTypeAnalysisReport.read(buf)
        }
    }

    override fun allocationSize(value: List<AnalysisReport>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeAnalysisReport.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<AnalysisReport>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeAnalysisReport.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeProbeScalar: FfiConverterRustBuffer<List<ProbeScalar>> {
    override fun read(buf: ByteBuffer): List<ProbeScalar> {
        val len = buf.getInt()
        return List<ProbeScalar>(len) {
            FfiConverterTypeProbeScalar.read(buf)
        }
    }

    override fun allocationSize(value: List<ProbeScalar>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeProbeScalar.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ProbeScalar>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeProbeScalar.write(it, buf)
        }
    }
}
    @Throws(SayehFfiException::class) fun `analyseMessage`(`text`: kotlin.String): List<AnalysisReport> {
            return FfiConverterSequenceTypeAnalysisReport.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_analyse_message(
        FfiConverterString.lower(`text`),_status)
}
    )
    }

 fun `analyseTransportProbe`(`text`: kotlin.String): ProbeReport {
            return FfiConverterTypeProbeReport.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_analyse_transport_probe(
        FfiConverterString.lower(`text`),_status)
}
    )
    }

 fun `generateTransportProbe`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_generate_transport_probe(
        _status)
}
    )
    }


    @Throws(SayehFfiException::class) fun `hidePasswordFile`(`cover`: kotlin.String, `fileName`: kotlin.String, `bytes`: kotlin.ByteArray, `password`: kotlin.String, `carrier`: CarrierChoice, `createdAt`: kotlin.ULong): HiddenMessage {
            return FfiConverterTypeHiddenMessage.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_hide_password_file(
        FfiConverterString.lower(`cover`),FfiConverterString.lower(`fileName`),FfiConverterByteArray.lower(`bytes`),FfiConverterString.lower(`password`),FfiConverterTypeCarrierChoice.lower(`carrier`),FfiConverterULong.lower(`createdAt`),_status)
}
    )
    }


    @Throws(SayehFfiException::class) fun `hidePasswordText`(`cover`: kotlin.String, `secret`: kotlin.String, `password`: kotlin.String, `carrier`: CarrierChoice, `createdAt`: kotlin.ULong): HiddenMessage {
            return FfiConverterTypeHiddenMessage.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_hide_password_text(
        FfiConverterString.lower(`cover`),FfiConverterString.lower(`secret`),FfiConverterString.lower(`password`),FfiConverterTypeCarrierChoice.lower(`carrier`),FfiConverterULong.lower(`createdAt`),_status)
}
    )
    }


    @Throws(SayehFfiException::class) fun `payloadCapacity`(`carrier`: CarrierChoice, `contactMode`: kotlin.Boolean, `fileNameBytes`: kotlin.ULong): CapacityReport {
            return FfiConverterTypeCapacityReport.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_payload_capacity(
        FfiConverterTypeCarrierChoice.lower(`carrier`),FfiConverterBoolean.lower(`contactMode`),FfiConverterULong.lower(`fileNameBytes`),_status)
}
    )
    }


    @Throws(SayehFfiException::class) fun `revealPasswordMessage`(`text`: kotlin.String, `password`: kotlin.String): OpenedMessage {
            return FfiConverterTypeOpenedMessage.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_reveal_password_message(
        FfiConverterString.lower(`text`),FfiConverterString.lower(`password`),_status)
}
    )
    }


    @Throws(SayehFfiException::class) fun `scanMessage`(`text`: kotlin.String): ScanReport {
            return FfiConverterTypeScanReport.lift(
    uniffiRustCallWithError(SayehFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_scan_message(
        FfiConverterString.lower(`text`),_status)
}
    )
    }

 fun `stripMessageAggressive`(`text`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_strip_message_aggressive(
        FfiConverterString.lower(`text`),_status)
}
    )
    }

 fun `stripMessageSafe`(`text`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_sayeh_ffi_fn_func_strip_message_safe(
        FfiConverterString.lower(`text`),_status)
}
    )
    }
